#!/bin/bash

CHECKLT_HOME=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if  uname | grep -iq CYGWIN
then
    JARFILE=`cygpath -w "$CHECKLT_HOME/lib/checkers.jar"`
    CLASSPATH=`cygpath -w "$CHECKLT_HOME/lib/checker-lattice-tainting-plugin.jar"`
else
    JARFILE="$CHECKLT_HOME/lib/checkers.jar"
    CLASSPATH="$CHECKLT_HOME/lib/checker-lattice-tainting-plugin.jar"
fi

java -jar "$JARFILE" -classpath "$CLASSPATH"  -processor checkers.latticetainting.LatticeTaintingChecker "$@"

